apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  suspend: true
  interval: 24h
  path: ./infrastructure
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
