---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: 0.29.1
  install:
    crds: Create
  interval: 24h
  upgrade:
    crds: Create
